// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: proto/cart/pb_cart.proto

package cartPb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CartItemProductSimple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku     string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty     int32  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	QuoteId string `protobuf:"bytes,3,opt,name=quoteId,proto3" json:"quoteId,omitempty"`
}

func (x *CartItemProductSimple) Reset() {
	*x = CartItemProductSimple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartItemProductSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemProductSimple) ProtoMessage() {}

func (x *CartItemProductSimple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemProductSimple.ProtoReflect.Descriptor instead.
func (*CartItemProductSimple) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItemProductSimple) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CartItemProductSimple) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CartItemProductSimple) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type AddItemProductSimpleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartItem *CartItemProductSimple `protobuf:"bytes,1,opt,name=cartItem,proto3" json:"cartItem,omitempty"`
}

func (x *AddItemProductSimpleRequest) Reset() {
	*x = AddItemProductSimpleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemProductSimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemProductSimpleRequest) ProtoMessage() {}

func (x *AddItemProductSimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemProductSimpleRequest.ProtoReflect.Descriptor instead.
func (*AddItemProductSimpleRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemProductSimpleRequest) GetCartItem() *CartItemProductSimple {
	if x != nil {
		return x.CartItem
	}
	return nil
}

type AddItemProductSimpleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId      int32   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sku         string  `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty         int32   `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Name        string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price       float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	ProductType string  `protobuf:"bytes,6,opt,name=productType,proto3" json:"productType,omitempty"`
	QuoteId     string  `protobuf:"bytes,7,opt,name=quoteId,proto3" json:"quoteId,omitempty"`
}

func (x *AddItemProductSimpleResponse) Reset() {
	*x = AddItemProductSimpleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemProductSimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemProductSimpleResponse) ProtoMessage() {}

func (x *AddItemProductSimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemProductSimpleResponse.ProtoReflect.Descriptor instead.
func (*AddItemProductSimpleResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemProductSimpleResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AddItemProductSimpleResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *AddItemProductSimpleResponse) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *AddItemProductSimpleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddItemProductSimpleResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddItemProductSimpleResponse) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *AddItemProductSimpleResponse) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type ConfigurableItemOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionId    string `protobuf:"bytes,1,opt,name=optionId,proto3" json:"optionId,omitempty"`
	OptionValue int32  `protobuf:"varint,2,opt,name=optionValue,proto3" json:"optionValue,omitempty"`
}

func (x *ConfigurableItemOptions) Reset() {
	*x = ConfigurableItemOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurableItemOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurableItemOptions) ProtoMessage() {}

func (x *ConfigurableItemOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurableItemOptions.ProtoReflect.Descriptor instead.
func (*ConfigurableItemOptions) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigurableItemOptions) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

func (x *ConfigurableItemOptions) GetOptionValue() int32 {
	if x != nil {
		return x.OptionValue
	}
	return 0
}

type ExtensionAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigurableItemOptions []*ConfigurableItemOptions `protobuf:"bytes,1,rep,name=configurableItemOptions,proto3" json:"configurableItemOptions,omitempty"`
}

func (x *ExtensionAttributes) Reset() {
	*x = ExtensionAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionAttributes) ProtoMessage() {}

func (x *ExtensionAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionAttributes.ProtoReflect.Descriptor instead.
func (*ExtensionAttributes) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{4}
}

func (x *ExtensionAttributes) GetConfigurableItemOptions() []*ConfigurableItemOptions {
	if x != nil {
		return x.ConfigurableItemOptions
	}
	return nil
}

type ProductOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExtensionAttributes *ExtensionAttributes `protobuf:"bytes,1,opt,name=extensionAttributes,proto3" json:"extensionAttributes,omitempty"`
}

func (x *ProductOption) Reset() {
	*x = ProductOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOption) ProtoMessage() {}

func (x *ProductOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOption.ProtoReflect.Descriptor instead.
func (*ProductOption) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{5}
}

func (x *ProductOption) GetExtensionAttributes() *ExtensionAttributes {
	if x != nil {
		return x.ExtensionAttributes
	}
	return nil
}

type CartItemProductConfigurable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku                 string               `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty                 int32                `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	QuoteId             string               `protobuf:"bytes,3,opt,name=quoteId,proto3" json:"quoteId,omitempty"`
	ProductOption       *ProductOption       `protobuf:"bytes,4,opt,name=productOption,proto3" json:"productOption,omitempty"`
	ExtensionAttributes *ExtensionAttributes `protobuf:"bytes,5,opt,name=extensionAttributes,proto3" json:"extensionAttributes,omitempty"`
}

func (x *CartItemProductConfigurable) Reset() {
	*x = CartItemProductConfigurable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartItemProductConfigurable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemProductConfigurable) ProtoMessage() {}

func (x *CartItemProductConfigurable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemProductConfigurable.ProtoReflect.Descriptor instead.
func (*CartItemProductConfigurable) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartItemProductConfigurable) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CartItemProductConfigurable) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CartItemProductConfigurable) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *CartItemProductConfigurable) GetProductOption() *ProductOption {
	if x != nil {
		return x.ProductOption
	}
	return nil
}

func (x *CartItemProductConfigurable) GetExtensionAttributes() *ExtensionAttributes {
	if x != nil {
		return x.ExtensionAttributes
	}
	return nil
}

type AddItemProductConfigurableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartItem *CartItemProductConfigurable `protobuf:"bytes,1,opt,name=cartItem,proto3" json:"cartItem,omitempty"`
}

func (x *AddItemProductConfigurableRequest) Reset() {
	*x = AddItemProductConfigurableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemProductConfigurableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemProductConfigurableRequest) ProtoMessage() {}

func (x *AddItemProductConfigurableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemProductConfigurableRequest.ProtoReflect.Descriptor instead.
func (*AddItemProductConfigurableRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{7}
}

func (x *AddItemProductConfigurableRequest) GetCartItem() *CartItemProductConfigurable {
	if x != nil {
		return x.CartItem
	}
	return nil
}

type AddItemProductConfigurableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId      int32  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sku         string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty         int32  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price       int32  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	ProductType string `protobuf:"bytes,6,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	QuoteId     string `protobuf:"bytes,7,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
}

func (x *AddItemProductConfigurableResponse) Reset() {
	*x = AddItemProductConfigurableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemProductConfigurableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemProductConfigurableResponse) ProtoMessage() {}

func (x *AddItemProductConfigurableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemProductConfigurableResponse.ProtoReflect.Descriptor instead.
func (*AddItemProductConfigurableResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{8}
}

func (x *AddItemProductConfigurableResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AddItemProductConfigurableResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *AddItemProductConfigurableResponse) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *AddItemProductConfigurableResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddItemProductConfigurableResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddItemProductConfigurableResponse) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *AddItemProductConfigurableResponse) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region        string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	RegionId      string   `protobuf:"bytes,2,opt,name=regionId,proto3" json:"regionId,omitempty"`
	RegionCode    string   `protobuf:"bytes,3,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	CountryId     string   `protobuf:"bytes,4,opt,name=countryId,proto3" json:"countryId,omitempty"`
	Street        []string `protobuf:"bytes,5,rep,name=street,proto3" json:"street,omitempty"`
	Postcode      string   `protobuf:"bytes,6,opt,name=postcode,proto3" json:"postcode,omitempty"`
	City          string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	FirstName     string   `protobuf:"bytes,8,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string   `protobuf:"bytes,9,opt,name=lastName,proto3" json:"lastName,omitempty"`
	CustomerId    int32    `protobuf:"varint,10,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Email         string   `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Telephone     string   `protobuf:"bytes,12,opt,name=telephone,proto3" json:"telephone,omitempty"`
	SameAsBilling int32    `protobuf:"varint,13,opt,name=sameAsBilling,proto3" json:"sameAsBilling,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{9}
}

func (x *Address) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Address) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *Address) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *Address) GetCountryId() string {
	if x != nil {
		return x.CountryId
	}
	return ""
}

func (x *Address) GetStreet() []string {
	if x != nil {
		return x.Street
	}
	return nil
}

func (x *Address) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Address) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Address) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Address) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Address) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *Address) GetSameAsBilling() int32 {
	if x != nil {
		return x.SameAsBilling
	}
	return 0
}

type EstimateShippingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EstimateShippingRequest) Reset() {
	*x = EstimateShippingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimateShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateShippingRequest) ProtoMessage() {}

func (x *EstimateShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateShippingRequest.ProtoReflect.Descriptor instead.
func (*EstimateShippingRequest) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{10}
}

func (x *EstimateShippingRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarrierCode  string `protobuf:"bytes,1,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	MethodCode   string `protobuf:"bytes,2,opt,name=method_code,json=methodCode,proto3" json:"method_code,omitempty"`
	CarrierTitle string `protobuf:"bytes,3,opt,name=carrier_title,json=carrierTitle,proto3" json:"carrier_title,omitempty"`
	MethodTitle  string `protobuf:"bytes,4,opt,name=method_title,json=methodTitle,proto3" json:"method_title,omitempty"`
	Amount       int32  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	BaseAmount   int32  `protobuf:"varint,6,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	Available    bool   `protobuf:"varint,7,opt,name=available,proto3" json:"available,omitempty"`
	ErrorMessage string `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PriceExclTax int32  `protobuf:"varint,9,opt,name=price_excl_tax,json=priceExclTax,proto3" json:"price_excl_tax,omitempty"`
	PriceInclTax int32  `protobuf:"varint,10,opt,name=price_incl_tax,json=priceInclTax,proto3" json:"price_incl_tax,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{11}
}

func (x *Data) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *Data) GetMethodCode() string {
	if x != nil {
		return x.MethodCode
	}
	return ""
}

func (x *Data) GetCarrierTitle() string {
	if x != nil {
		return x.CarrierTitle
	}
	return ""
}

func (x *Data) GetMethodTitle() string {
	if x != nil {
		return x.MethodTitle
	}
	return ""
}

func (x *Data) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Data) GetBaseAmount() int32 {
	if x != nil {
		return x.BaseAmount
	}
	return 0
}

func (x *Data) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Data) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Data) GetPriceExclTax() int32 {
	if x != nil {
		return x.PriceExclTax
	}
	return 0
}

func (x *Data) GetPriceInclTax() int32 {
	if x != nil {
		return x.PriceInclTax
	}
	return 0
}

type EstimateShippingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *EstimateShippingResponse) Reset() {
	*x = EstimateShippingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cart_pb_cart_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimateShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateShippingResponse) ProtoMessage() {}

func (x *EstimateShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_pb_cart_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateShippingResponse.ProtoReflect.Descriptor instead.
func (*EstimateShippingResponse) Descriptor() ([]byte, []int) {
	return file_proto_cart_pb_cart_proto_rawDescGZIP(), []int{12}
}

func (x *EstimateShippingResponse) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_cart_pb_cart_proto protoreflect.FileDescriptor

var file_proto_cart_pb_cart_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x70, 0x62, 0x5f,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x55, 0x0a, 0x15, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22,
	0xc1, 0x01, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x6f,
	0x74, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6f, 0x0a, 0x13,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x12, 0x58, 0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x17, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5d, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4c,
	0x0a, 0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0xe5, 0x01, 0x0a,
	0x1b, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10,
	0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x0d, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52,
	0x13, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x22, 0x63, 0x0a, 0x21, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x08, 0x63, 0x61, 0x72,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x08, 0x63, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0xc9, 0x01, 0x0a, 0x22, 0x41, 0x64,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x49, 0x64, 0x22, 0xf7, 0x02, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x61, 0x6d,
	0x65, 0x41, 0x73, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x73, 0x61, 0x6d, 0x65, 0x41, 0x73, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22,
	0x43, 0x0a, 0x17, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0xda, 0x02, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65,
	0x72, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x65,
	0x78, 0x63, 0x6c, 0x5f, 0x74, 0x61, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x45, 0x78, 0x63, 0x6c, 0x54, 0x61, 0x78, 0x12, 0x24, 0x0a, 0x0e, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x5f, 0x74, 0x61, 0x78, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x6c, 0x54, 0x61,
	0x78, 0x22, 0x3b, 0x0a, 0x18, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xad,
	0x03, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x8d, 0x01, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x22, 0x21, 0x2f, 0x72, 0x65,
	0x73, 0x74, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x56, 0x31, 0x2f, 0x63, 0x61,
	0x72, 0x74, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x65, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x3a, 0x01,
	0x2a, 0x12, 0xa3, 0x01, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x22, 0x25, 0x2f,
	0x72, 0x65, 0x73, 0x74, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x56, 0x31, 0x2f,
	0x63, 0x61, 0x72, 0x74, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x65, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x2f, 0x63, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x65, 0x0a, 0x10, 0x45, 0x73, 0x74, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x53, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0a, 0x22, 0x05, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x08,
	0x5a, 0x06, 0x63, 0x61, 0x72, 0x74, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cart_pb_cart_proto_rawDescOnce sync.Once
	file_proto_cart_pb_cart_proto_rawDescData = file_proto_cart_pb_cart_proto_rawDesc
)

func file_proto_cart_pb_cart_proto_rawDescGZIP() []byte {
	file_proto_cart_pb_cart_proto_rawDescOnce.Do(func() {
		file_proto_cart_pb_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cart_pb_cart_proto_rawDescData)
	})
	return file_proto_cart_pb_cart_proto_rawDescData
}

var file_proto_cart_pb_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_cart_pb_cart_proto_goTypes = []interface{}{
	(*CartItemProductSimple)(nil),              // 0: proto.CartItemProductSimple
	(*AddItemProductSimpleRequest)(nil),        // 1: proto.AddItemProductSimpleRequest
	(*AddItemProductSimpleResponse)(nil),       // 2: proto.AddItemProductSimpleResponse
	(*ConfigurableItemOptions)(nil),            // 3: proto.ConfigurableItemOptions
	(*ExtensionAttributes)(nil),                // 4: proto.ExtensionAttributes
	(*ProductOption)(nil),                      // 5: proto.ProductOption
	(*CartItemProductConfigurable)(nil),        // 6: proto.CartItemProductConfigurable
	(*AddItemProductConfigurableRequest)(nil),  // 7: proto.AddItemProductConfigurableRequest
	(*AddItemProductConfigurableResponse)(nil), // 8: proto.AddItemProductConfigurableResponse
	(*Address)(nil),                            // 9: proto.Address
	(*EstimateShippingRequest)(nil),            // 10: proto.EstimateShippingRequest
	(*Data)(nil),                               // 11: proto.Data
	(*EstimateShippingResponse)(nil),           // 12: proto.EstimateShippingResponse
}
var file_proto_cart_pb_cart_proto_depIdxs = []int32{
	0,  // 0: proto.AddItemProductSimpleRequest.cartItem:type_name -> proto.CartItemProductSimple
	3,  // 1: proto.ExtensionAttributes.configurableItemOptions:type_name -> proto.ConfigurableItemOptions
	4,  // 2: proto.ProductOption.extensionAttributes:type_name -> proto.ExtensionAttributes
	5,  // 3: proto.CartItemProductConfigurable.productOption:type_name -> proto.ProductOption
	4,  // 4: proto.CartItemProductConfigurable.extensionAttributes:type_name -> proto.ExtensionAttributes
	6,  // 5: proto.AddItemProductConfigurableRequest.cartItem:type_name -> proto.CartItemProductConfigurable
	9,  // 6: proto.EstimateShippingRequest.address:type_name -> proto.Address
	11, // 7: proto.EstimateShippingResponse.data:type_name -> proto.Data
	1,  // 8: proto.AddItemProduct.AddItemProductSimple:input_type -> proto.AddItemProductSimpleRequest
	7,  // 9: proto.AddItemProduct.AddItemProductConfigurable:input_type -> proto.AddItemProductConfigurableRequest
	10, // 10: proto.AddItemProduct.EstimateShipping:input_type -> proto.EstimateShippingRequest
	2,  // 11: proto.AddItemProduct.AddItemProductSimple:output_type -> proto.AddItemProductSimpleResponse
	8,  // 12: proto.AddItemProduct.AddItemProductConfigurable:output_type -> proto.AddItemProductConfigurableResponse
	12, // 13: proto.AddItemProduct.EstimateShipping:output_type -> proto.EstimateShippingResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_cart_pb_cart_proto_init() }
func file_proto_cart_pb_cart_proto_init() {
	if File_proto_cart_pb_cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cart_pb_cart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartItemProductSimple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemProductSimpleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemProductSimpleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigurableItemOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtensionAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartItemProductConfigurable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemProductConfigurableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemProductConfigurableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimateShippingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cart_pb_cart_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimateShippingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cart_pb_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cart_pb_cart_proto_goTypes,
		DependencyIndexes: file_proto_cart_pb_cart_proto_depIdxs,
		MessageInfos:      file_proto_cart_pb_cart_proto_msgTypes,
	}.Build()
	File_proto_cart_pb_cart_proto = out.File
	file_proto_cart_pb_cart_proto_rawDesc = nil
	file_proto_cart_pb_cart_proto_goTypes = nil
	file_proto_cart_pb_cart_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddItemProductClient is the client API for AddItemProduct service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddItemProductClient interface {
	AddItemProductSimple(ctx context.Context, in *AddItemProductSimpleRequest, opts ...grpc.CallOption) (*AddItemProductSimpleResponse, error)
	AddItemProductConfigurable(ctx context.Context, in *AddItemProductConfigurableRequest, opts ...grpc.CallOption) (*AddItemProductConfigurableResponse, error)
	EstimateShipping(ctx context.Context, in *EstimateShippingRequest, opts ...grpc.CallOption) (*EstimateShippingResponse, error)
}

type addItemProductClient struct {
	cc grpc.ClientConnInterface
}

func NewAddItemProductClient(cc grpc.ClientConnInterface) AddItemProductClient {
	return &addItemProductClient{cc}
}

func (c *addItemProductClient) AddItemProductSimple(ctx context.Context, in *AddItemProductSimpleRequest, opts ...grpc.CallOption) (*AddItemProductSimpleResponse, error) {
	out := new(AddItemProductSimpleResponse)
	err := c.cc.Invoke(ctx, "/proto.AddItemProduct/AddItemProductSimple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addItemProductClient) AddItemProductConfigurable(ctx context.Context, in *AddItemProductConfigurableRequest, opts ...grpc.CallOption) (*AddItemProductConfigurableResponse, error) {
	out := new(AddItemProductConfigurableResponse)
	err := c.cc.Invoke(ctx, "/proto.AddItemProduct/AddItemProductConfigurable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addItemProductClient) EstimateShipping(ctx context.Context, in *EstimateShippingRequest, opts ...grpc.CallOption) (*EstimateShippingResponse, error) {
	out := new(EstimateShippingResponse)
	err := c.cc.Invoke(ctx, "/proto.AddItemProduct/EstimateShipping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddItemProductServer is the server API for AddItemProduct service.
type AddItemProductServer interface {
	AddItemProductSimple(context.Context, *AddItemProductSimpleRequest) (*AddItemProductSimpleResponse, error)
	AddItemProductConfigurable(context.Context, *AddItemProductConfigurableRequest) (*AddItemProductConfigurableResponse, error)
	EstimateShipping(context.Context, *EstimateShippingRequest) (*EstimateShippingResponse, error)
}

// UnimplementedAddItemProductServer can be embedded to have forward compatible implementations.
type UnimplementedAddItemProductServer struct {
}

func (*UnimplementedAddItemProductServer) AddItemProductSimple(context.Context, *AddItemProductSimpleRequest) (*AddItemProductSimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItemProductSimple not implemented")
}
func (*UnimplementedAddItemProductServer) AddItemProductConfigurable(context.Context, *AddItemProductConfigurableRequest) (*AddItemProductConfigurableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItemProductConfigurable not implemented")
}
func (*UnimplementedAddItemProductServer) EstimateShipping(context.Context, *EstimateShippingRequest) (*EstimateShippingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateShipping not implemented")
}

func RegisterAddItemProductServer(s *grpc.Server, srv AddItemProductServer) {
	s.RegisterService(&_AddItemProduct_serviceDesc, srv)
}

func _AddItemProduct_AddItemProductSimple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemProductSimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddItemProductServer).AddItemProductSimple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddItemProduct/AddItemProductSimple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddItemProductServer).AddItemProductSimple(ctx, req.(*AddItemProductSimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddItemProduct_AddItemProductConfigurable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemProductConfigurableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddItemProductServer).AddItemProductConfigurable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddItemProduct/AddItemProductConfigurable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddItemProductServer).AddItemProductConfigurable(ctx, req.(*AddItemProductConfigurableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddItemProduct_EstimateShipping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateShippingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddItemProductServer).EstimateShipping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddItemProduct/EstimateShipping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddItemProductServer).EstimateShipping(ctx, req.(*EstimateShippingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddItemProduct_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddItemProduct",
	HandlerType: (*AddItemProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItemProductSimple",
			Handler:    _AddItemProduct_AddItemProductSimple_Handler,
		},
		{
			MethodName: "AddItemProductConfigurable",
			Handler:    _AddItemProduct_AddItemProductConfigurable_Handler,
		},
		{
			MethodName: "EstimateShipping",
			Handler:    _AddItemProduct_EstimateShipping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cart/pb_cart.proto",
}
